/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ecn;

public class App {
    public static void main(String[] args) {
        var board = new Board();
        System.out.println(board);
    }
}
